[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | venv
  | migrations
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
skip = ["venv", "migrations", "__pycache__"]

[tool.ruff]
exclude = ["venv", "migrations", "__pycache__"]
line-length = 88

[tool.mypy]
exclude = '.*settings\.py$'
plugins = ["mypy_django_plugin.main"]
strict = true

[tool.django-stubs]
django_settings_module = "shop_drf.settings"

[tool.mypy-rest_framework]
ignore_missing_imports = true